// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrMJMjQOyFxb9aVrLgaCpcsRgPRmBsPI',
    appId: '1:676282203129:web:89f7015ffd664771a0db28',
    messagingSenderId: '676282203129',
    projectId: 'opet-penguasa-lautan',
    authDomain: 'opet-penguasa-lautan.firebaseapp.com',
    databaseURL: 'https://opet-penguasa-lautan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'opet-penguasa-lautan.firebasestorage.app',
    measurementId: 'G-TKNHM3K4XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYsCw0y0hmklwfhOm5eEIUXh8iLOw-IMs',
    appId: '1:676282203129:android:b2be77a9e43fd38ca0db28',
    messagingSenderId: '676282203129',
    projectId: 'opet-penguasa-lautan',
    databaseURL: 'https://opet-penguasa-lautan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'opet-penguasa-lautan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cUIPvI6SZ6h3Mu96ZptQhr99TX51SzI',
    appId: '1:676282203129:ios:cf6e71aeb02970d0a0db28',
    messagingSenderId: '676282203129',
    projectId: 'opet-penguasa-lautan',
    databaseURL: 'https://opet-penguasa-lautan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'opet-penguasa-lautan.firebasestorage.app',
    iosBundleId: 'com.example.iotUiChallenge',
  );
}
